[package]
name = "fork_model"
version = "0.1.1"
edition = "2021"
authors = ["Oliver <oli.harris@outlook.com>"]
repository = "https://github.com/olitanium/fork-model.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

