[package]
name = "fork_model"
version = "0.0.1"
edition = "2021"
authors = ["Oliver <o.harris@techmodal.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

